# Site settings
title: Zernerda Bot
description: –í–Ω—É—à–∏—Ç–µ–ª—å–Ω—ã–π –Ω–∞–±–æ—Ä —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª–∞ –¥–ª—è "–ø—Ä–æ–±–∏–≤–∞" –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –∏ —Å–∞–º–∞—è –±–æ–ª—å—à–∞—è –±–∞–∑–∞ –¥–∞–Ω–Ω—ã—Ö.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zernerda Bot
# user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: –£–Ω–∏–∫–∞–ª—å–Ω—ã–µ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –≤ –ø—Ä–æ–±–∏–≤–∞! –ß—Ç–æ–±—ã –≤–æ—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –±–æ—Ç–æ–º, –Ω–∞–∂–º–∏—Ç–µ –Ω–∞ –∏–∫–æ–Ω–∫—É Telegram –≤–Ω–∏–∑—É üëá
# email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

